apiVersion: v1
kind: Secret
metadata:
  name: permitio-pdp-secret
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ApiKey: {{ .Values.pdp.ApiKey | b64enc | quote }}
