{{- if not .Values.pdp.existingApiKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdp.secretName" . }}
  labels:
    {{- include "pdp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "pdp.secretKey" . }}: {{ .Values.pdp.ApiKey | b64enc | quote }}
{{- end }}
