apiVersion: v1
kind: Service
metadata:
  name: permitio-pdp
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: permitio-pdp
  ports:
    - protocol: TCP
      port: {{ .Values.pdp.port }}
      targetPort: 7000
