name: Build and publish to Docker Hub
on:
  # push:
  #   branches:
  #     - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # ====== Todos Backend (build and deploy) ======
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: permitio/pdp:latest
          context: .
          file: ./Dockerfile
          #All available platforms: linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          platforms: linux/arm64,linux/amd64
          build-args: |
            READ_ONLY_GITHUB_TOKEN=${{ secrets.READ_ONLY_GITHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
